### ISSUE TITLE
Preview Replacements

### ISSUE THREAD

**Issue by davidrgarza** [ExpandedFronts/Better-Search-Replace#12]
Hello,

It would be very helpful to preview the before/after replacement.

**Comment by mgshaw** [comment]
@davidrgarza Thanks for the feedback! I think this is a great idea and will definitely look into this further.

**Comment by davidrgarza** [comment]
@mgshaw Thanks for following-up :+1:

**Comment by mgshaw** [comment]
Closing as this has been completed with the pro version available starting with v1.1. Can't do everything for free :)
